merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/update/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),

    path('contact-us/', views.contact, name='contact'),
    path('about-us/', views.about_us, name='about'),

    path('email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(
        choices=Genre.choices,
        max_length=5
    )
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    #like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

class Listing(models.Model):

    class Type(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISC = 'M'

    title = models.CharField(max_length=100)
    types = models.CharField(
        choices=Type.choices,
        max_length=15
    )
    description = models.CharField(max_length=1000)
    year = models.IntegerField(
        null=True, 
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    sold = models.BooleanField(default=False)
    band = models.ForeignKey(Band, on_delete=models.SET_NULL, null=True)


merchex/listings/forms.py
from django import forms

from listings.models import Band, Listing

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ['active', 'official_homepage']

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ['sold']

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.core.mail import send_mail

from listings.models import Listing
from listings.models import Band
from listings.forms import BandForm, ContactUsForm, ListingForm

## Band views
def band_list(request):
    bands = Band.objects.all()
    return render(request, 
                  'listings/band_list.html', 
                  {'bands': bands})

def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, 
                  'listings/band_detail.html', 
                  {'band': band})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request,
            'listings/band_create.html',
            {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance = band)
    return render(request,
                  'listings/band_update.html',
                  {'form': form})

def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('band-list')
    return render(request,
                  'listings/band_delete.html',
                  {'band': band})

## Listing views
def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 
                  'listings/listing_list.html', 
                  {'listings': listings})

def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 
                  'listings/listing_detail.html', 
                  {'listing': listing})

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)  
    else:
        form = ListingForm()
    return render(request,
            'listings/listing_create.html',
            {'form': form})

def listing_update(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance = listing)
    return render(request,
                  'listings/listing_update.html',
                  {'form': form})

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')
    return render(request,
                  'listings/listing_delete.html',
                  {'listing': listing})

## Contact views
def contact(request):

    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "Anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
                )
            return redirect('email-sent')
    else:
        form = ContactUsForm()
    
    return render(request, 
                  'listings/contact.html',
                  {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')


## About views
def about_us(request):
    return render(request, 'listings/about_us.html')

merchex/listings/templates/listings/about_us.html
{% extends "listings/base.html" %} {% block content %}
<h1>About US</h1>
<p>Apropos de nous</p>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends "listings/base.html" %} {% block content %}
<h1>Créer un groupe</h1>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Créer" />
</form>
{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %} {% block content %}
<h1>Delete Band</h1>
<p>Are you sure you want to delete {{ band.name }}?</p>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Confirm" />
</form>
{% endblock %} ```

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %} {% block content %}
<h2>{{ band.name }}</h2>
<a href="{% url 'band-update' band.id %}">[editer]</a>
<a href="{% url 'band-delete' band.id %}">[supprimer]</a>
<ul>
  <li>Genre : {{ band.get_genre_display }}</li>
  <li>Année de formtation : {{ band.year_formed }}</li>
  <li>Actif : {{ band.active|yesno }}</li>
  {% if band.official_homepage %}
  <li>
    <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a>
  </li>
  {% endif %}
</ul>

<p>{{ band.biography }}</p>

<ul>
  {% for listing in band.listing_set.all %}
  <li>
    <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
  </li>
  {% endfor %}
</ul>

<a href="{% url 'band-list' %}">Retour à la liste des groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends "listings/base.html" %} {% block content %}
<h1>Groupes</h1>
<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<ul>
  {% for band in bands %}
  <li>
    <a href="{% url 'band-detail' band.id %}"> {{ band.name }} </a>
    -
    <a href="{% url 'band-update' band.id %}"> [editer] </a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends "listings/base.html" %} {% block content %}
<h1>Modifier un groupe</h1>
<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Modifier" />
</form>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <title>Mercheex</title>
  </head>
  <body>
    <nav>
      <a href="{% url 'band-list' %}">Groupes</a>
      <a href="{% url 'listing-list' %}">Liste</a>
      <a href="{% url 'contact' %}">Contact</a>
      <a href="{% url 'about' %}">à propos</a>
    </nav>

    {% block content %}{% endblock %}
  </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends "listings/base.html" %} {% block content %}
<h1>Contact US</h1>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Envoyer" />
</form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends "listings/base.html" %} {% block content %}
<h1>Message envoyé</h1>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends "listings/base.html" %} {% block content %}
<h1>Créer une annonce</h1>
<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Créer" />
</form>
{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %} {% block content %}
<h1>Delete Listing</h1>
<p>Are you sure you want to delete {{ band.name }}?</p>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Confirm" />
</form>
{% endblock %} ```

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %} {% block content %}
<h2>{{ listing.title }}</h2>
<a href="{% url 'listing-update' listing.id %}">[editer]</a>
<a href="{% url 'listing-delete' listing.id %}">[supprimer]</a>

<ul>
  <li>Type : {{ listing.get_types_display }}</li>
  <li>Année : {{ listing.year }}</li>
  <li>Vendu : {{ listing.sold|yesno }}</li>
  {% if listing.band %}
  <li>
    <a href="{% url 'band-detail' listing.band.id %}">{{ listing.band }}</a>
  </li>
  {% endif %}
</ul>

<p>{{ listing.descritpion }}</p>

<a href="{% url 'listing-list' %}">Retour à la liste des annonces</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends "listings/base.html" %} {% block content %}
<h1>Linsting</h1>
<a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>
<ul>
  {% for listing in listings %}
  <li>
    <a href="{% url 'listing-detail' listing.id%}">{{ listing.title }}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends "listings/base.html" %} {% block content %}
<h1>Modifier une annonce</h1>
<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Modifier" />
</form>
{% endblock %}